version: "3.7"
services:
    dev:
        build:
            context: .
            dockerfile: Dockerfile.dev
        volumes:
            - type: bind
              source: .git
              target: /host/jade/.git
        devices:
            - "/dev/ttyUSB0:/dev/ttyUSB0"
        privileged: true
        tty: true
